apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: simple-hpa
  namespace: ingress-nginx
data:
  # Add for simple-hpa
  disable-access-log: "false"
  access-log-path: "syslog:server=simple-hpa.hpa:514"
  log-format-upstream:  '{"time_str": "$time_iso8601",
                          "time_msec": $msec,
                          "remote_addr": "$proxy_protocol_addr",
                          "x-forward-for": "$http_x_forwarded_for",
                          "request_time": $request_time,
                          "upstream_response_time": "$upstream_response_time",
                          "upstream_addr": "$upstream_addr",
                          "status": $status,
                          "hostname": "$host",
                          "namespace": "$namespace",
                          "service": "$service_name"}'