apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-hpa
  name: simple-hpa
spec:
  # Don't change
  replicas: 1
  selector:
    matchLabels:
      app: simple-hpa
  template:
    metadata:
      labels:
        app: simple-hpa
    spec:
      containers:
        - image: {{ .Values.image.hub }}/simple-hpa:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: simple-hpa
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: INGRESS_TYPE
              value: "nginx"
            - name: MIN_POD
              value: "1"
            - name: MAX_POD
              value: "2"
            - name: MAX_QPS
              value: "10"
            - name: SAFE_QPS
              value: "5"
            - name: SCALE_SERVICES
              value: service-mesh.solar-controller
          ports:
            - containerPort: 514
              name: rsyslog
              protocol: UDP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
---

