apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-hpa
  name: simple-hpa
spec:
  ports:
    - port: 514
      protocol: UDP
      targetPort: 514
  selector:
    app: simple-hpa
  sessionAffinity: None
  type: ClusterIP