ingressType: nginx

listen:
  port: 514
  address: 0.0.0.0

default:
  # QPS采样频率，即每5秒取一次样，单位为秒
  avgTime: 5
  # 自动扩展的间隔时间，防止频繁升降，单位为秒
  scaleIntervalTime: 120
  # 限制最高Pod数
  maxPod: 2
  minPod: 1
  # QPS达到该值开始自动伸缩
  maxQps: 5
  # QPS安全值，将Pod的QPS伸缩到该值。如果Pod太多，也会基于该值减少
  safeQps: 2
  # TODO 这一块要优化
  # 影响因子。用于测试验证，怕流量太大处理不过来，只接入部分流量时，计算会 * factor
  factor: 1

# use env ServiceName.Namespace:minPod:maxPod:safeQps:maxQps:factor
scaleServices:
  # 需要自动伸缩的服务
  - serviceName: ServiceName1
    namespace: namespace1
    # 未指定项将使用默认值
    maxPod: 10
    minPod: 6
    maxQps: 25
    safeQps: 20
    # factor: 1

  - serviceName: ServiceName2
    namespace: namespace2
    maxPod: 10
    minPod: 6
    maxQps: 25
    safeQps: 20

  - serviceName: daohao
    namespace: demo-dev
    factor: 2
    # other use default

# Deployment指定的environment优先级会高于config.yaml

# 将Ingres AccessLog转发，用于如分析日志场景
#forwards:
#  - type: rsyslog
#    address: 128.0.255.10:514