listen:
  port: 514
  address: 0.0.0.0

ingressType: nginx
# QPS采样频率，即每5秒取一次样，单位为秒
avgTime: 5
# 自动扩展的间隔时间，防止频繁升降，单位为秒
scaleIntervalTime: 120

autoScale:
  # 限制最高Pod数
  maxPod: 20
  minPod: 1
  # QPS达到该值开始自动伸缩
  maxQPS: 10
  # QPS安全值，将Pod的QPS伸缩到该值。如果Pod太多，也会基于该值减少
  safeQPS: 6
  # 需要HPA的服务
  services:
    - namespace.deployName
    - default.sample-app
    - demo-dev.daohao
    - demo.client

# Deployment指定的environment优先级会高于config.yaml