apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auto-scale
  name: auto-scale
spec:
  # Don't change
  replicas: 1
  selector:
    matchLabels:
      app: auto-scale
  template:
    metadata:
      labels:
        app: auto-scale
    spec:
      containers:
        - image: unknowname/auto-scale
          imagePullPolicy: Always
          name: auto-scale
          env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: AVG_TIME
            value: "5"
          - name: INGRESS_TYPE
            value: "nginx"
          - name: MIN_POD
            value: "35"
          - name: MAX_POD
            value: "40"
          - name: MAX_QPS
            value: "10"
          - name: SAFE_QPS
            value: "5"
          - name: SCALE_INTERVAL_TIME
            value: "120"
          - name: SCALE_SERVICES
            # Service.Namespace:minPod:maxPod:safeQPS:maxQPS:factor,another
            value: "wxd.sixunmall-web-host:1:2:10:20:1"
          - name: FORWARDS
            # "TypeName=IP:Port,another"
            value: ""
          ports:
            - containerPort: 514
              name: rsyslog
              protocol: UDP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-scale
  name: auto-scale
spec:
  ports:
    - port: 514
      protocol: UDP
      targetPort: 514
  selector:
    app: auto-scale
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: auto-scale
rules:
  - apiGroups:
      - '*'
    resources:
      - 'deployments'
    verbs:
      - 'get'
      - 'update'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: auto-scale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auto-scale
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
