apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-hpa
  name: simple-hpa
spec:
  # Don't change
  replicas: 1
  selector:
    matchLabels:
      app: simple-hpa
  template:
    metadata:
      labels:
        app: simple-hpa
    spec:
      containers:
        - image: docker.sixun.hw:5000/siss/simple-hpa
          imagePullPolicy: Always
          name: simple-hpa
          env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: AVG_TIME
            value: "5"
          - name: INGRESS_TYPE
            value: "nginx"
          - name: MIN_POD
            value: "35"
          - name: MAX_POD
            value: "40"
          - name: MAX_QPS
            value: "10"
          - name: SAFE_QPS
            value: "5"
          - name: SCALE_INTERVAL_TIME
            value: "120"
          - name: SCALE_SERVICES
            # Namespace.ServiceName
            value: "wxd.sixunmall-web-host"
          - name: FORWARDS
            # "TypeName:IP:Port"
            value: ""
          ports:
            - containerPort: 514
              name: rsyslog
              protocol: UDP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-hpa
  name: simple-hpa
spec:
  ports:
    - port: 514
      protocol: UDP
      targetPort: 514
  selector:
    app: simple-hpa
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: simple-hpa
rules:
  - apiGroups:
      - '*'
    resources:
      - 'deployments'
    verbs:
      - 'get'
      - 'update'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: simple-hpa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simple-hpa
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
