apiVersion: v1
kind: Pod
metadata:
  name: simple-hpa
spec:
  containers:
    - image: unknowname/simple-hpa
      imagePullPolicy: Always
      name: simple-hpa
      env:
        - name: MAX_POD
          value: "2"
        - name: MIN_POD
          value: "1"
        - name: SAFE_QPS
          value: "5"
        - name: MAX_QPS
          value: "10"
        - name: SCALE_SERVICES
          value: "deme-dev.daohao,namespace.test"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30